# Generated by Django 3.1.3 on 2020-12-02 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.CharField(max_length=3)),
                ('numero_identidad', models.CharField(max_length=15, unique=True)),
                ('numero_celular', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.CharField(max_length=3)),
                ('numero_identidad', models.CharField(max_length=15, unique=True)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_personas', models.IntegerField()),
                ('codigo_reserva', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_identidad_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.cliente', to_field='numero_identidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=7)),
                ('valor', models.IntegerField()),
                ('codigo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.itemmenu', to_field='codigo_item')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('total_cuenta', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_identidad_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.cliente', to_field='numero_identidad')),
            ],
        ),
    ]
