# Generated by Django 3.1.3 on 2020-12-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='estado_reservacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
