# Generated by Django 3.1.3 on 2020-12-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_reservacion_estado_reservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
